# Jekyll configuration file

# default options for pages
defaults:
    -
        # for all pages in the project
        scope:
            path: ''
        values:
            layout: 'page'

# Jekyll plugins
gems:
    - jekyll-sass-converter
    - jekyll-seo-tag

